SMS_TO_NUMBER = "+491737005007"
SMS_FROM_NUMBER = "+4917693627539"
SMS_COMMAND_FROM_NUMBER = "+491737005007"
SEND_TO_URL = "http://54.225.70.237/"

VALUEFORMAT = {
    'bartrend': "b",
    'barometer': "H",
    'insidetemperature': "h",
    'insidehumidity': "B",
    'outsidetemperature': "h",
    'outsidehumidity': "B",
    'windspeed': "B",
    'winddirection': "H",
    '2mavgwindspeed': "H",
    '10mavgwindspeed': "H",
    '10mwindgust': "H",
    'winddirectionfor10mwindgust': "H",
    'dewpoint': "h",
    'heatindex': "h",
    'windchill': "h",
    'rainrate': "H",
    'uvindex': "b",
    'solarradiation': "H",
    'stormrain': "H",
    'startdateofcurrentstorm': "H",
    'dailyrain': "H",
    'monthlyrain': "H",
    'yearlyrain': "H",
    'last15mrain': "H",
    'lasthourrain': "H",
    'last24hrain': "H",
    'dailyet': "H",
    'monthlyet': "H",
    'yearlyet': "H",
    'timeofsunrise': "H",
    'timeofsunset': "H",
    'transmitterbatterystatus': "b",
    'consolebatteryvoltage': "H",
    }

VALUES = (
    'bartrend',
    'barometer',
    'insidetemperature',
    'insidehumidity',
    'outsidetemperature',
    'outsidehumidity',
    'windspeed',
    'winddirection',
    '2mavgwindspeed',
    '10mavgwindspeed',
    '10mwindgust',
    'winddirectionfor10mwindgust',
    'dewpoint',
    'heatindex',
    'windchill',
    'rainrate',
    'uvindex',
    'solarradiation',
    'stormrain',
    'startdateofcurrentstorm',
    'dailyrain',
    'monthlyrain',
    'yearlyrain',
    'last15mrain',
    'lasthourrain',
    'last24hrain',
    'dailyet',
    'monthlyet',
    'yearlyet',
    'timeofsunrise',
    'timeofsunset',
    'transmitterbatterystatus',
    'consolebatteryvoltage',
    )
