# define the format of all possible values (python struct format)
VALUEFORMAT = {
                'bartrend': "b",
                'barometer': "H",
                'insidetemperature': "h",
                'insidehumidity': "B",
                'outsidetemperature': "h",
                'outsidehumidity': "B",
                'windspeed': "B",
                'winddirection': "H",
                '2mavgwindspeed': "H",
                '10mavgwindspeed': "H",
                '10mwindgust': "H",
                'winddirectionfor10mwindgust': "H",
                'dewpoint': "h",
                'heatindex': "h",
                'windchill': "h",
                'rainrate': "H",
                'uvindex': "b",
                'solarradiation': "H",
                'stormrain': "H",
                'startdateofcurrentstorm': "H",
                'dailyrain': "H",
                'monthlyrain': "H",
                'yearlyrain': "H",
                'last15mrain': "H",
                'lasthourrain': "H",
                'last24hrain': "H",
                'dailyet': "H",
                'monthlyet': "H",
                'yearlyet': "H",
                'timeofsunrise': "H",
                'timeofsunset': "H",
                'transmitterbatterystatus': "b",
                'consolebatteryvoltage': "H",
                }
# define which data will be send
VALUES = [
        {
            # type of message (0-255)
            # 0 - Davis Vantage Vue Loop/Loop2 data
            'type': 0,
            # which measurements are included in this message, define the order
            'values': (
                'bartrend',
                'barometer',
                'insidetemperature',
                'insidehumidity',
                'outsidetemperature',
                'outsidehumidity',
                'windspeed',
                'winddirection',
                '2mavgwindspeed',
                '10mavgwindspeed',
                '10mwindgust',
                'winddirectionfor10mwindgust',
                'dewpoint',
                'heatindex',
                'windchill',
                'rainrate',
                'uvindex',
                'solarradiation',
                'stormrain',
                'startdateofcurrentstorm',
                'dailyrain',
                'monthlyrain',
                'yearlyrain',
                'last15mrain',
                'lasthourrain',
                'last24hrain',
                'dailyet',
                'monthlyet',
                'yearlyet',
                'timeofsunrise',
                'timeofsunset',
                'transmitterbatterystatus',
                'consolebatteryvoltage',
                )
        },
        # add other data formats here
    ]
